const bcrypt = require('bcryptjs');
const {
  sequelize, User, ChemistryExperiment, PhysicsSimulation, BiologyLab,
  LabEquipment, LabReport, SafetyTraining, StudentProgress, DataAnalysis,
  MolecularStructure, Assessment, Collaboration, LabSchedule, ResearchPaper,
  VirtualLabSession
} = require('../models');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database synced successfully');

    // Users
    const hashedPassword = await bcrypt.hash('password123', 10);
    await User.bulkCreate([
      { email: 'admin@ailab.edu', password: hashedPassword, firstName: 'Admin', lastName: 'User', role: 'admin' },
      { email: 'instructor@ailab.edu', password: hashedPassword, firstName: 'Dr. Sarah', lastName: 'Chen', role: 'instructor' },
      { email: 'student@ailab.edu', password: hashedPassword, firstName: 'Alex', lastName: 'Johnson', role: 'student' }
    ]);
    console.log('Users seeded');

    // Chemistry Experiments (15)
    await ChemistryExperiment.bulkCreate([
      { name: 'Acid-Base Titration', description: 'Determine the concentration of an unknown acid using a standardized base solution', reactants: 'HCl, NaOH, Phenolphthalein', products: 'NaCl, H2O', difficulty: 'beginner', category: 'Analytical Chemistry', safetyLevel: 'Medium', estimatedTime: '45 min' },
      { name: 'Electrochemical Cell Construction', description: 'Build a galvanic cell and measure electrode potentials', reactants: 'Zn, Cu, ZnSO4, CuSO4', products: 'Zn²⁺, Cu', difficulty: 'intermediate', category: 'Electrochemistry', safetyLevel: 'Medium', estimatedTime: '60 min' },
      { name: 'Synthesis of Aspirin', description: 'Synthesize acetylsalicylic acid from salicylic acid and acetic anhydride', reactants: 'Salicylic acid, Acetic anhydride, H3PO4', products: 'Aspirin, Acetic acid', difficulty: 'advanced', category: 'Organic Chemistry', safetyLevel: 'High', estimatedTime: '90 min' },
      { name: 'Flame Test Analysis', description: 'Identify metal ions by their characteristic flame colors', reactants: 'LiCl, NaCl, KCl, CaCl2, CuCl2, BaCl2', products: 'Various colored flames', difficulty: 'beginner', category: 'Qualitative Analysis', safetyLevel: 'Medium', estimatedTime: '30 min' },
      { name: 'Calorimetry - Heat of Reaction', description: 'Measure the enthalpy change of a neutralization reaction using a calorimeter', reactants: 'HCl, NaOH', products: 'NaCl, H2O, Heat', difficulty: 'intermediate', category: 'Thermochemistry', safetyLevel: 'Low', estimatedTime: '50 min' },
      { name: 'Crystal Growth Lab', description: 'Grow single crystals of copper sulfate from supersaturated solution', reactants: 'CuSO4·5H2O, Water', products: 'CuSO4 crystals', difficulty: 'beginner', category: 'Solid State Chemistry', safetyLevel: 'Low', estimatedTime: '120 min' },
      { name: 'Reaction Kinetics - Iodine Clock', description: 'Study reaction rates by measuring the time for the iodine clock reaction', reactants: 'KIO3, NaHSO3, Starch', products: 'Iodine-starch complex', difficulty: 'intermediate', category: 'Kinetics', safetyLevel: 'Low', estimatedTime: '55 min' },
      { name: 'Distillation of Ethanol', description: 'Separate ethanol from water using fractional distillation', reactants: 'Ethanol-water mixture', products: 'Pure ethanol, Water', difficulty: 'advanced', category: 'Separation Techniques', safetyLevel: 'High', estimatedTime: '75 min' },
      { name: 'pH Buffer Preparation', description: 'Prepare and test buffer solutions with different pH values', reactants: 'Acetic acid, Sodium acetate, HCl, NaOH', products: 'Buffer solutions', difficulty: 'intermediate', category: 'Acid-Base Chemistry', safetyLevel: 'Low', estimatedTime: '40 min' },
      { name: 'Gravimetric Analysis of Chloride', description: 'Determine chloride content by precipitation with silver nitrate', reactants: 'NaCl sample, AgNO3', products: 'AgCl precipitate', difficulty: 'advanced', category: 'Analytical Chemistry', safetyLevel: 'Medium', estimatedTime: '80 min' },
      { name: 'Polymer Synthesis - Nylon', description: 'Synthesize nylon 6,10 by interfacial polymerization', reactants: 'Hexamethylenediamine, Sebacoyl chloride', products: 'Nylon 6,10', difficulty: 'advanced', category: 'Polymer Chemistry', safetyLevel: 'High', estimatedTime: '45 min' },
      { name: 'Le Chatelier Principle Demo', description: 'Observe equilibrium shifts by changing temperature, concentration, and pressure', reactants: 'CoCl2, HCl, Water', products: 'Co(H2O)6²⁺ ⇌ CoCl4²⁻', difficulty: 'beginner', category: 'Equilibrium', safetyLevel: 'Low', estimatedTime: '35 min' },
      { name: 'Spectrophotometry - Beer\'s Law', description: 'Determine concentration using UV-Vis spectrophotometry and Beer-Lambert law', reactants: 'KMnO4 solutions', products: 'Absorbance data', difficulty: 'intermediate', category: 'Instrumental Analysis', safetyLevel: 'Low', estimatedTime: '50 min' },
      { name: 'Redox Reactions Series', description: 'Explore oxidation-reduction reactions with various metals and solutions', reactants: 'Cu, Zn, Fe, AgNO3, CuSO4, FeSO4', products: 'Various metal deposits', difficulty: 'beginner', category: 'Redox Chemistry', safetyLevel: 'Medium', estimatedTime: '40 min' },
      { name: 'Gas Laws Verification', description: 'Verify Boyle\'s, Charles\'s, and Gay-Lussac\'s laws experimentally', reactants: 'Air, Water', products: 'P-V-T data', difficulty: 'beginner', category: 'Physical Chemistry', safetyLevel: 'Low', estimatedTime: '60 min' }
    ]);
    console.log('Chemistry experiments seeded');

    // Physics Simulations (15)
    await PhysicsSimulation.bulkCreate([
      { name: 'Projectile Motion Simulator', description: 'Simulate projectile trajectories with adjustable angle, velocity, and air resistance', category: 'Mechanics', parameters: 'angle, velocity, mass, air resistance', formula: 'x = v₀cos(θ)t, y = v₀sin(θ)t - ½gt²', difficulty: 'beginner', estimatedTime: '30 min' },
      { name: 'Simple Harmonic Motion', description: 'Model spring-mass systems and pendulum oscillations', category: 'Mechanics', parameters: 'mass, spring constant, amplitude, damping', formula: 'x(t) = A·cos(ωt + φ)', difficulty: 'intermediate', estimatedTime: '35 min' },
      { name: 'Electric Field Visualization', description: 'Visualize electric field lines around point charges and charge distributions', category: 'Electromagnetism', parameters: 'charge magnitude, position, number of charges', formula: 'E = kQ/r²', difficulty: 'intermediate', estimatedTime: '40 min' },
      { name: 'Wave Interference Patterns', description: 'Simulate constructive and destructive interference of waves', category: 'Waves', parameters: 'wavelength, amplitude, phase, frequency', formula: 'y = A₁sin(kx-ωt) + A₂sin(kx-ωt+φ)', difficulty: 'intermediate', estimatedTime: '35 min' },
      { name: 'Thermodynamic Cycles', description: 'Simulate Carnot, Otto, and Diesel engine cycles on PV diagrams', category: 'Thermodynamics', parameters: 'temperature, pressure, volume, gas type', formula: 'η = 1 - Tc/Th', difficulty: 'advanced', estimatedTime: '50 min' },
      { name: 'Optics - Ray Tracing', description: 'Trace light rays through lenses and mirrors with adjustable parameters', category: 'Optics', parameters: 'focal length, object distance, lens type', formula: '1/f = 1/do + 1/di', difficulty: 'beginner', estimatedTime: '30 min' },
      { name: 'Circular Motion & Gravity', description: 'Simulate orbital mechanics and gravitational interactions between bodies', category: 'Mechanics', parameters: 'mass, radius, velocity, gravitational constant', formula: 'F = GMm/r²', difficulty: 'advanced', estimatedTime: '45 min' },
      { name: 'RC Circuit Simulator', description: 'Model charging and discharging of capacitors in RC circuits', category: 'Circuits', parameters: 'resistance, capacitance, voltage', formula: 'V(t) = V₀(1 - e^(-t/RC))', difficulty: 'intermediate', estimatedTime: '40 min' },
      { name: 'Nuclear Decay Simulation', description: 'Simulate radioactive decay and half-life calculations', category: 'Nuclear Physics', parameters: 'initial amount, half-life, decay type', formula: 'N(t) = N₀e^(-λt)', difficulty: 'advanced', estimatedTime: '35 min' },
      { name: 'Doppler Effect Demo', description: 'Visualize frequency shifts for moving sound and light sources', category: 'Waves', parameters: 'source frequency, source velocity, observer velocity', formula: 'f\' = f(v ± vo)/(v ± vs)', difficulty: 'beginner', estimatedTime: '25 min' },
      { name: 'Magnetic Field Simulator', description: 'Visualize magnetic fields around wires, solenoids, and magnets', category: 'Electromagnetism', parameters: 'current, wire geometry, permeability', formula: 'B = μ₀I/(2πr)', difficulty: 'intermediate', estimatedTime: '40 min' },
      { name: 'Fluid Dynamics - Bernoulli', description: 'Simulate fluid flow and pressure variations in pipes', category: 'Fluid Mechanics', parameters: 'fluid density, velocity, pipe diameter', formula: 'P + ½ρv² + ρgh = const', difficulty: 'advanced', estimatedTime: '45 min' },
      { name: 'Collision Physics Lab', description: 'Model elastic and inelastic collisions in 1D and 2D', category: 'Mechanics', parameters: 'mass1, mass2, velocity1, velocity2, type', formula: 'm₁v₁ + m₂v₂ = m₁v₁\' + m₂v₂\'', difficulty: 'beginner', estimatedTime: '30 min' },
      { name: 'Standing Waves on String', description: 'Simulate standing wave formation on a vibrating string', category: 'Waves', parameters: 'string length, tension, linear density, frequency', formula: 'fₙ = n/(2L)√(T/μ)', difficulty: 'intermediate', estimatedTime: '35 min' },
      { name: 'Photoelectric Effect', description: 'Simulate the photoelectric effect and determine Planck\'s constant', category: 'Quantum Physics', parameters: 'light frequency, metal work function, intensity', formula: 'KE = hf - φ', difficulty: 'advanced', estimatedTime: '40 min' }
    ]);
    console.log('Physics simulations seeded');

    // Biology Labs (15)
    await BiologyLab.bulkCreate([
      { name: 'Cell Division - Mitosis', description: 'Observe and identify stages of mitosis in onion root tip cells', organism: 'Allium cepa', labType: 'Cell Biology', difficulty: 'beginner', equipment: 'Microscope, Slides, Staining kit', procedures: 'Prepare slide, stain with acetocarmine, observe under microscope' },
      { name: 'DNA Extraction', description: 'Extract and visualize DNA from strawberries using household chemicals', organism: 'Fragaria ananassa', labType: 'Molecular Biology', difficulty: 'beginner', equipment: 'Beakers, Cheesecloth, Ethanol, Dish soap', procedures: 'Mash fruit, add extraction buffer, filter, add cold ethanol' },
      { name: 'Bacterial Culture & Gram Stain', description: 'Culture bacteria and differentiate using Gram staining technique', organism: 'E. coli, S. aureus', labType: 'Microbiology', difficulty: 'intermediate', equipment: 'Petri dishes, Incubator, Gram stain kit', procedures: 'Inoculate plates, incubate, prepare smear, Gram stain protocol' },
      { name: 'Photosynthesis Rate Measurement', description: 'Measure the rate of photosynthesis under different light conditions', organism: 'Elodea canadensis', labType: 'Plant Biology', difficulty: 'intermediate', equipment: 'Aquatic plants, Light source, Graduated cylinder', procedures: 'Submerge plant, vary light intensity, count oxygen bubbles' },
      { name: 'Enzyme Kinetics - Catalase', description: 'Study enzyme activity and factors affecting reaction rate', organism: 'Bovine liver', labType: 'Biochemistry', difficulty: 'intermediate', equipment: 'Liver samples, H2O2, Test tubes, Timer', procedures: 'Prepare enzyme solution, vary substrate concentration, measure O2 production' },
      { name: 'Heart Dissection', description: 'Virtual dissection of mammalian heart to study cardiac anatomy', organism: 'Sus scrofa (pig)', labType: 'Anatomy', difficulty: 'intermediate', equipment: 'Dissection kit, Heart specimen, Pins, Tray', procedures: 'External examination, identify vessels, open chambers, trace blood flow' },
      { name: 'Osmosis & Diffusion Lab', description: 'Investigate osmosis in potato cells at different concentrations', organism: 'Solanum tuberosum', labType: 'Cell Biology', difficulty: 'beginner', equipment: 'Potato cores, Sucrose solutions, Balance, Beakers', procedures: 'Cut potato cores, weigh, place in solutions, reweigh after 30 min' },
      { name: 'Genetic Crosses - Drosophila', description: 'Perform monohybrid and dihybrid crosses with fruit flies', organism: 'Drosophila melanogaster', labType: 'Genetics', difficulty: 'advanced', equipment: 'Fly vials, Anesthetizer, Microscope, Medium', procedures: 'Select parent phenotypes, set up crosses, count F1 and F2 offspring' },
      { name: 'Blood Typing Lab', description: 'Determine ABO and Rh blood types using antibody reactions', organism: 'Human (simulated)', labType: 'Immunology', difficulty: 'beginner', equipment: 'Blood typing slides, Anti-A, Anti-B, Anti-Rh sera', procedures: 'Add antisera to blood samples, observe agglutination patterns' },
      { name: 'Ecosystem in a Bottle', description: 'Create a self-sustaining ecosystem and monitor changes over time', organism: 'Multiple species', labType: 'Ecology', difficulty: 'beginner', equipment: 'Large bottles, Plants, Water, Small organisms', procedures: 'Layer gravel and soil, add plants and water, seal, observe weekly' },
      { name: 'Protein Electrophoresis', description: 'Separate proteins using SDS-PAGE gel electrophoresis', organism: 'Various samples', labType: 'Biochemistry', difficulty: 'advanced', equipment: 'Gel apparatus, Power supply, Protein samples, Staining solution', procedures: 'Prepare gel, load samples, run electrophoresis, stain and analyze' },
      { name: 'Respiration Rate in Germinating Seeds', description: 'Measure cellular respiration rates using a respirometer', organism: 'Pisum sativum', labType: 'Plant Biology', difficulty: 'intermediate', equipment: 'Respirometer, Seeds, KOH, Glass beads', procedures: 'Set up respirometer with germinating seeds, measure O2 consumption' },
      { name: 'Ecological Sampling Methods', description: 'Practice quadrat and transect sampling techniques', organism: 'Field organisms', labType: 'Ecology', difficulty: 'beginner', equipment: 'Quadrats, Transect tapes, Identification guides', procedures: 'Set up quadrats, count species, calculate diversity indices' },
      { name: 'PCR Amplification', description: 'Amplify a specific DNA segment using polymerase chain reaction', organism: 'Lambda phage DNA', labType: 'Molecular Biology', difficulty: 'advanced', equipment: 'Thermal cycler, PCR tubes, Primers, Taq polymerase', procedures: 'Set up PCR reaction, program thermal cycler, run gel electrophoresis' },
      { name: 'Microscopy Skills Lab', description: 'Master microscopy techniques with various specimen types', organism: 'Multiple specimens', labType: 'General Biology', difficulty: 'beginner', equipment: 'Compound microscope, Prepared slides, Cover slips', procedures: 'Focus techniques, oil immersion, measure specimens with ocular micrometer' }
    ]);
    console.log('Biology labs seeded');

    // Lab Equipment (15)
    await LabEquipment.bulkCreate([
      { name: 'Digital Microscope Pro 4000', description: 'High-resolution digital microscope with 40x-1000x magnification and image capture', category: 'Microscopy', manufacturer: 'LabVision Inc', modelNumber: 'DMP-4000', status: 'available', location: 'Room 201', virtualAvailable: true },
      { name: 'Analytical Balance', description: 'Precision balance with 0.0001g readability for quantitative measurements', category: 'Measurement', manufacturer: 'MettlerTech', modelNumber: 'AB-204S', status: 'available', location: 'Room 105', virtualAvailable: true },
      { name: 'UV-Vis Spectrophotometer', description: 'Double-beam spectrophotometer for absorbance and transmittance measurements', category: 'Spectroscopy', manufacturer: 'SpectraCorp', modelNumber: 'UV-2600', status: 'available', location: 'Room 302', virtualAvailable: true },
      { name: 'Centrifuge High-Speed', description: 'Refrigerated centrifuge capable of 25,000 RPM for sample separation', category: 'Separation', manufacturer: 'BioSpin', modelNumber: 'HS-25K', status: 'in-use', location: 'Room 204', virtualAvailable: true },
      { name: 'PCR Thermal Cycler', description: 'Programmable thermal cycler for DNA amplification with 96-well block', category: 'Molecular Biology', manufacturer: 'GeneTech', modelNumber: 'TC-96Plus', status: 'available', location: 'Room 401', virtualAvailable: true },
      { name: 'Fume Hood - Chemical Safety', description: 'Ducted fume hood with variable airflow for chemical handling safety', category: 'Safety', manufacturer: 'SafeAir Systems', modelNumber: 'FH-1200', status: 'available', location: 'Room 105', virtualAvailable: false },
      { name: 'Gel Electrophoresis System', description: 'Complete system for protein and nucleic acid electrophoresis', category: 'Molecular Biology', manufacturer: 'BioRad', modelNumber: 'GE-200', status: 'available', location: 'Room 401', virtualAvailable: true },
      { name: 'pH Meter Digital', description: 'Benchtop pH meter with automatic temperature compensation', category: 'Measurement', manufacturer: 'AccuMeter', modelNumber: 'pH-700', status: 'available', location: 'Room 105', virtualAvailable: true },
      { name: 'Autoclave Steam Sterilizer', description: 'High-pressure steam sterilizer for laboratory equipment and media', category: 'Sterilization', manufacturer: 'SterTech', modelNumber: 'AC-300', status: 'maintenance', location: 'Room 102', virtualAvailable: false },
      { name: 'Oscilloscope Digital', description: '200MHz 4-channel digital oscilloscope for signal analysis', category: 'Electronics', manufacturer: 'WaveForm', modelNumber: 'DS-2204', status: 'available', location: 'Room 501', virtualAvailable: true },
      { name: 'Incubator CO2', description: 'CO2 incubator for cell culture with humidity and temperature control', category: 'Cell Culture', manufacturer: 'CellGrow', modelNumber: 'IC-160', status: 'in-use', location: 'Room 403', virtualAvailable: false },
      { name: 'Rotary Evaporator', description: 'Rotary evaporator for efficient solvent removal under vacuum', category: 'Chemistry', manufacturer: 'RotaVap', modelNumber: 'RE-501', status: 'available', location: 'Room 302', virtualAvailable: true },
      { name: 'Calorimeter Bomb', description: 'Bomb calorimeter for measuring heat of combustion reactions', category: 'Thermochemistry', manufacturer: 'ThermoLab', modelNumber: 'BC-100', status: 'available', location: 'Room 201', virtualAvailable: true },
      { name: 'Laser Optics Kit', description: 'Complete optics set with lasers, lenses, mirrors, and diffraction gratings', category: 'Optics', manufacturer: 'PhotonLab', modelNumber: 'LOK-500', status: 'available', location: 'Room 501', virtualAvailable: true },
      { name: 'Mass Spectrometer', description: 'Benchtop mass spectrometer for molecular identification and analysis', category: 'Spectroscopy', manufacturer: 'MassSpec Inc', modelNumber: 'MS-3000', status: 'available', location: 'Room 302', virtualAvailable: true }
    ]);
    console.log('Lab equipment seeded');

    // Lab Reports (15)
    await LabReport.bulkCreate([
      { title: 'Acid-Base Titration of Unknown HCl', studentName: 'Emily Watson', subject: 'Chemistry', hypothesis: 'The unknown acid concentration can be determined through titration with standardized NaOH', methodology: 'Titrated 25mL aliquots of unknown HCl with 0.1M NaOH using phenolphthalein indicator', results: 'Average endpoint: 22.3mL NaOH. Calculated HCl concentration: 0.089M', conclusion: 'Successfully determined the unknown acid concentration with 2.3% error from the accepted value', grade: 'A' },
      { title: 'Projectile Motion Analysis', studentName: 'Marcus Chen', subject: 'Physics', hypothesis: 'Launch angle of 45° produces maximum range', methodology: 'Launched steel ball at angles 15°-75° in 15° increments, measured range', results: 'Maximum range at 45° (2.34m), consistent with theoretical prediction', conclusion: 'Experimental results confirm theoretical prediction within 5% error margin', grade: 'A-' },
      { title: 'Mitosis in Onion Root Tips', studentName: 'Sarah Park', subject: 'Biology', hypothesis: 'Most cells will be observed in interphase due to its longer duration', methodology: 'Prepared and stained onion root tip squash slides, counted 200 cells per slide', results: '82% interphase, 8% prophase, 5% metaphase, 3% anaphase, 2% telophase', conclusion: 'Results support hypothesis; interphase is the longest phase of the cell cycle', grade: 'A' },
      { title: 'Enzyme Kinetics of Catalase', studentName: 'James Rodriguez', subject: 'Biochemistry', hypothesis: 'Enzyme activity increases with substrate concentration following Michaelis-Menten kinetics', methodology: 'Measured O2 production at varying H2O2 concentrations with liver catalase', results: 'Km = 25mM, Vmax = 12.5 μmol/min. Lineweaver-Burk plot showed good linearity', conclusion: 'Catalase follows Michaelis-Menten kinetics with competitive inhibition by azide', grade: 'B+' },
      { title: 'Simple Harmonic Motion of Pendulum', studentName: 'Priya Sharma', subject: 'Physics', hypothesis: 'Period depends only on length, not mass or amplitude for small angles', methodology: 'Varied mass (50-200g), length (0.2-1.0m), and amplitude (5°-15°), measured period', results: 'Period vs length: T = 2.01√L. No significant effect from mass or small amplitude changes', conclusion: 'Confirmed that period depends on length, matching theoretical prediction T=2π√(L/g)', grade: 'A' },
      { title: 'DNA Extraction from Strawberries', studentName: 'Tyler Brown', subject: 'Biology', hypothesis: 'DNA can be extracted using simple detergent-based lysis and ethanol precipitation', methodology: 'Mashed strawberries, added extraction buffer (soap, salt, water), filtered, added cold ethanol', results: 'Successfully extracted visible DNA strands. Estimated yield: 15μg from 10g tissue', conclusion: 'Household chemicals effectively extract plant DNA; octaploid strawberries yield high amounts', grade: 'B+' },
      { title: 'RC Circuit Time Constants', studentName: 'Hannah Kim', subject: 'Physics', hypothesis: 'The time constant τ = RC determines charging/discharging rate', methodology: 'Built RC circuits with varying R and C values, measured voltage across capacitor vs time', results: 'Measured τ values within 8% of theoretical. Exponential fits R² > 0.98', conclusion: 'RC time constant accurately predicts circuit behavior; deviations due to component tolerances', grade: 'A-' },
      { title: 'Osmosis in Potato Cells', studentName: 'Daniel Lee', subject: 'Biology', hypothesis: 'Potato cells will gain mass in hypotonic solutions and lose mass in hypertonic solutions', methodology: 'Placed uniform potato cores in 0-1.0M sucrose solutions for 30 minutes', results: 'Mass gain in 0-0.2M, equilibrium at ~0.3M, mass loss in 0.4-1.0M solutions', conclusion: 'Results confirm osmosis principles; estimated cell sap concentration is approximately 0.3M', grade: 'A' },
      { title: 'Crystal Growth Parameters', studentName: 'Sofia Martinez', subject: 'Chemistry', hypothesis: 'Slower cooling rates produce larger, more well-formed crystals', methodology: 'Grew CuSO4 crystals at three cooling rates: rapid, moderate, and slow over 7 days', results: 'Slow cooling: 2.3cm crystals, Moderate: 1.1cm, Rapid: 0.4cm average size', conclusion: 'Confirmed slower nucleation favors growth of fewer, larger crystals', grade: 'A' },
      { title: 'Wave Interference and Diffraction', studentName: 'Alex Rivera', subject: 'Physics', hypothesis: 'Double slit spacing determines fringe width according to λ = d·sin(θ)', methodology: 'Used laser pointer with double slits of varying separation, measured fringe patterns', results: 'Measured λ = 648±12nm (nominal 650nm). Inverse relationship between d and fringe width confirmed', conclusion: 'Successfully determined laser wavelength and verified wave nature of light', grade: 'B+' },
      { title: 'Gram Staining Bacterial Identification', studentName: 'Maria Gonzalez', subject: 'Microbiology', hypothesis: 'Unknown bacteria can be classified as Gram-positive or Gram-negative by staining', methodology: 'Applied Gram stain protocol to known and unknown bacterial smears', results: 'Unknown A: Gram-positive cocci (likely Staphylococcus). Unknown B: Gram-negative rods (likely E. coli)', conclusion: 'Gram stain remains a fundamental diagnostic tool; results consistent with further biochemical tests', grade: 'A-' },
      { title: 'Calorimetry - Heat of Neutralization', studentName: 'Kevin Thompson', subject: 'Chemistry', hypothesis: 'Strong acid-strong base neutralization releases approximately 57.1 kJ/mol', methodology: 'Mixed equal volumes of 1M HCl and 1M NaOH in a calorimeter, measured temperature change', results: 'ΔT = 6.8°C, calculated ΔH = -55.3 kJ/mol', conclusion: 'Measured value within 3.2% of literature value; heat loss to surroundings is the main error source', grade: 'B+' },
      { title: 'Photosynthesis Light Reactions', studentName: 'Amy Zhang', subject: 'Biology', hypothesis: 'Photosynthesis rate increases with light intensity up to a saturation point', methodology: 'Measured O2 bubble rate from Elodea at different light distances (inverse square law)', results: 'Rate increased linearly to 2000 lux, then plateaued. Max rate: 18 bubbles/min', conclusion: 'Light intensity is a limiting factor until other factors (CO2, temperature) become limiting', grade: 'A' },
      { title: 'Spectrophotometric Analysis of KMnO4', studentName: 'Robert Wilson', subject: 'Chemistry', hypothesis: 'A linear Beer-Lambert relationship exists for KMnO4 at 525nm', methodology: 'Measured absorbance of 5-50mg/L KMnO4 solutions at 525nm, created calibration curve', results: 'Beer\'s Law obeyed up to 40mg/L (R²=0.9987). Molar absorptivity ε = 2.43×10³ L/mol·cm', conclusion: 'Spectrophotometry is reliable for KMnO4 quantification within the linear range', grade: 'A-' },
      { title: 'Genetic Crosses in Drosophila', studentName: 'Jessica Nguyen', subject: 'Genetics', hypothesis: 'F2 phenotype ratios will follow Mendelian 3:1 for monohybrid cross', methodology: 'Crossed wild-type × vestigial wing flies, counted F1 and F2 offspring over 3 weeks', results: 'F1: all wild-type. F2: 312 wild-type, 98 vestigial (3.18:1). Chi-square p > 0.05', conclusion: 'Results support Mendelian inheritance; vestigial wing is autosomal recessive', grade: 'A' }
    ]);
    console.log('Lab reports seeded');

    // Safety Training (15)
    await SafetyTraining.bulkCreate([
      { title: 'Chemical Spill Response', description: 'Learn proper procedures for handling chemical spills in the laboratory', category: 'Emergency Response', hazardType: 'Chemical', procedures: '1. Alert others 2. Identify chemical 3. Use appropriate spill kit 4. Ventilate area 5. Document incident', passingScore: 80 },
      { title: 'Fire Safety & Extinguisher Use', description: 'Understand fire classifications and proper extinguisher operation', category: 'Fire Safety', hazardType: 'Fire', procedures: '1. RACE protocol 2. Identify fire class 3. PASS technique 4. Evacuation routes', passingScore: 85 },
      { title: 'Personal Protective Equipment', description: 'Selection and proper use of PPE for different laboratory hazards', category: 'PPE', hazardType: 'Multiple', procedures: '1. Risk assessment 2. PPE selection 3. Proper donning 4. Inspection 5. Proper doffing', passingScore: 80 },
      { title: 'Biological Safety - BSL-2', description: 'Biosafety level 2 practices and containment procedures', category: 'Biosafety', hazardType: 'Biological', procedures: '1. Biosafety cabinet use 2. Decontamination 3. Sharps handling 4. Waste disposal', passingScore: 90 },
      { title: 'Compressed Gas Cylinder Safety', description: 'Safe handling, storage, and use of compressed gas cylinders', category: 'Gas Safety', hazardType: 'Pressure/Chemical', procedures: '1. Cylinder inspection 2. Proper transport 3. Regulator attachment 4. Leak testing 5. Storage', passingScore: 85 },
      { title: 'Electrical Safety in Lab', description: 'Preventing electrical hazards and proper equipment grounding', category: 'Electrical Safety', hazardType: 'Electrical', procedures: '1. Equipment inspection 2. Grounding verification 3. GFCI use 4. Lockout/tagout basics', passingScore: 80 },
      { title: 'Hazardous Waste Disposal', description: 'Proper classification, labeling, and disposal of hazardous laboratory waste', category: 'Waste Management', hazardType: 'Chemical/Biological', procedures: '1. Waste classification 2. Container selection 3. Labeling 4. Segregation 5. Pickup scheduling', passingScore: 85 },
      { title: 'Radiation Safety Fundamentals', description: 'Basic radiation safety principles for labs using radioactive materials', category: 'Radiation Safety', hazardType: 'Radiation', procedures: '1. ALARA principle 2. Shielding 3. Dosimetry 4. Contamination surveys 5. Waste management', passingScore: 90 },
      { title: 'Cryogenic Material Handling', description: 'Safe handling of liquid nitrogen and other cryogenic materials', category: 'Cryogenic Safety', hazardType: 'Cold/Pressure', procedures: '1. PPE for cryogenics 2. Transfer procedures 3. Storage protocols 4. First aid for cold burns', passingScore: 85 },
      { title: 'Laboratory Ergonomics', description: 'Preventing repetitive strain and maintaining proper posture in lab work', category: 'Ergonomics', hazardType: 'Physical', procedures: '1. Workstation setup 2. Pipetting techniques 3. Microscope posture 4. Break scheduling', passingScore: 75 },
      { title: 'Chemical Storage Compatibility', description: 'Understanding chemical compatibility groups and proper storage practices', category: 'Chemical Safety', hazardType: 'Chemical', procedures: '1. SDS review 2. Compatibility groups 3. Storage cabinet selection 4. Quantity limits 5. Inspection', passingScore: 85 },
      { title: 'Emergency Eyewash & Shower Use', description: 'Proper use of emergency eyewash stations and safety showers', category: 'Emergency Equipment', hazardType: 'Chemical/Biological', procedures: '1. Location awareness 2. Activation procedure 3. Duration (15 min minimum) 4. Follow-up care', passingScore: 80 },
      { title: 'Laser Safety Training', description: 'Understanding laser classifications and safety procedures', category: 'Laser Safety', hazardType: 'Optical/Radiation', procedures: '1. Laser classification 2. Beam hazards 3. Protective eyewear 4. Controlled areas 5. Alignment procedures', passingScore: 85 },
      { title: 'Earthquake Preparedness in Lab', description: 'Securing equipment and responding to seismic events in the laboratory', category: 'Natural Disaster', hazardType: 'Seismic', procedures: '1. Equipment securing 2. Drop-Cover-Hold 3. Chemical containment 4. Evacuation 5. Damage assessment', passingScore: 80 },
      { title: 'First Aid Basics for Lab', description: 'Essential first aid procedures for common laboratory injuries', category: 'First Aid', hazardType: 'Multiple', procedures: '1. Burns treatment 2. Cuts and punctures 3. Chemical exposure 4. Eye injuries 5. When to call EMS', passingScore: 80 }
    ]);
    console.log('Safety training seeded');

    // Student Progress (15)
    await StudentProgress.bulkCreate([
      { studentName: 'Emily Watson', email: 'ewatson@ailab.edu', course: 'General Chemistry', completedLabs: 12, totalLabs: 15, averageScore: 92.5, lastActive: new Date('2026-03-15'), strengths: 'Analytical techniques, Lab report writing', improvements: 'Time management during experiments' },
      { studentName: 'Marcus Chen', email: 'mchen@ailab.edu', course: 'Physics I', completedLabs: 10, totalLabs: 15, averageScore: 88.0, lastActive: new Date('2026-03-14'), strengths: 'Data analysis, Mathematical modeling', improvements: 'Equipment handling, Error analysis' },
      { studentName: 'Sarah Park', email: 'spark@ailab.edu', course: 'Cell Biology', completedLabs: 14, totalLabs: 15, averageScore: 95.0, lastActive: new Date('2026-03-16'), strengths: 'Microscopy, Cell identification', improvements: 'None - excellent performance' },
      { studentName: 'James Rodriguez', email: 'jrodriguez@ailab.edu', course: 'Biochemistry', completedLabs: 8, totalLabs: 15, averageScore: 78.5, lastActive: new Date('2026-03-10'), strengths: 'Theoretical understanding', improvements: 'Practical lab techniques, Enzyme assay precision' },
      { studentName: 'Priya Sharma', email: 'psharma@ailab.edu', course: 'Physics II', completedLabs: 11, totalLabs: 15, averageScore: 91.0, lastActive: new Date('2026-03-15'), strengths: 'Circuit analysis, Wave optics', improvements: 'Report formatting' },
      { studentName: 'Tyler Brown', email: 'tbrown@ailab.edu', course: 'Molecular Biology', completedLabs: 9, totalLabs: 15, averageScore: 82.0, lastActive: new Date('2026-03-12'), strengths: 'PCR techniques', improvements: 'Gel electrophoresis interpretation, Sterile technique' },
      { studentName: 'Hannah Kim', email: 'hkim@ailab.edu', course: 'Electronics Lab', completedLabs: 13, totalLabs: 15, averageScore: 89.5, lastActive: new Date('2026-03-16'), strengths: 'Circuit design, Oscilloscope use', improvements: 'Soldering skills' },
      { studentName: 'Daniel Lee', email: 'dlee@ailab.edu', course: 'General Biology', completedLabs: 15, totalLabs: 15, averageScore: 94.0, lastActive: new Date('2026-03-17'), strengths: 'Excellent overall performance', improvements: 'Could explore advanced topics' },
      { studentName: 'Sofia Martinez', email: 'smartinez@ailab.edu', course: 'Organic Chemistry', completedLabs: 7, totalLabs: 15, averageScore: 75.0, lastActive: new Date('2026-03-08'), strengths: 'Crystal growth, Recrystallization', improvements: 'Synthesis techniques, Yield optimization' },
      { studentName: 'Alex Rivera', email: 'arivera@ailab.edu', course: 'Optics Lab', completedLabs: 11, totalLabs: 15, averageScore: 86.5, lastActive: new Date('2026-03-13'), strengths: 'Optical alignment, Data collection', improvements: 'Statistical error analysis' },
      { studentName: 'Maria Gonzalez', email: 'mgonzalez@ailab.edu', course: 'Microbiology', completedLabs: 13, totalLabs: 15, averageScore: 90.0, lastActive: new Date('2026-03-16'), strengths: 'Staining techniques, Culture methods', improvements: 'Antibiotic susceptibility testing' },
      { studentName: 'Kevin Thompson', email: 'kthompson@ailab.edu', course: 'Physical Chemistry', completedLabs: 6, totalLabs: 15, averageScore: 73.0, lastActive: new Date('2026-03-07'), strengths: 'Thermochemistry calculations', improvements: 'Calorimetry technique, Lab safety awareness' },
      { studentName: 'Amy Zhang', email: 'azhang@ailab.edu', course: 'Plant Biology', completedLabs: 14, totalLabs: 15, averageScore: 96.0, lastActive: new Date('2026-03-17'), strengths: 'Outstanding research skills, Publication-quality reports', improvements: 'None - top performer' },
      { studentName: 'Robert Wilson', email: 'rwilson@ailab.edu', course: 'Analytical Chemistry', completedLabs: 10, totalLabs: 15, averageScore: 84.0, lastActive: new Date('2026-03-11'), strengths: 'Spectrophotometry, Quantitative analysis', improvements: 'Gravimetric techniques, Significant figures' },
      { studentName: 'Jessica Nguyen', email: 'jnguyen@ailab.edu', course: 'Genetics', completedLabs: 12, totalLabs: 15, averageScore: 93.0, lastActive: new Date('2026-03-15'), strengths: 'Drosophila genetics, Chi-square analysis', improvements: 'Molecular genetics techniques' }
    ]);
    console.log('Student progress seeded');

    // Data Analysis (15)
    await DataAnalysis.bulkCreate([
      { title: 'Titration Curve Analysis', description: 'Statistical analysis of acid-base titration data', dataType: 'Quantitative', dataset: 'pH vs volume NaOH added (0-50mL)', method: 'Sigmoidal regression', results: 'Equivalence point: 22.3mL, pKa: 4.75', visualization: 'Line Chart' },
      { title: 'Enzyme Activity vs Temperature', description: 'Determine optimal temperature for catalase activity', dataType: 'Quantitative', dataset: 'Temperature (10-80°C) vs reaction rate', method: 'Polynomial regression', results: 'Optimal temp: 37°C, Activation energy: 32.5 kJ/mol', visualization: 'Line Chart' },
      { title: 'Species Diversity Index', description: 'Calculate Shannon-Wiener diversity index for field samples', dataType: 'Ecological', dataset: 'Species counts from 20 quadrats', method: 'Shannon-Wiener Index', results: 'H\' = 2.34, Evenness = 0.78', visualization: 'Bar Chart' },
      { title: 'Radioactive Decay Curve', description: 'Fit exponential decay model to simulated radioactive decay data', dataType: 'Quantitative', dataset: 'Time vs remaining nuclei count', method: 'Exponential regression', results: 'Half-life: 14.3 days, λ = 0.0485 day⁻¹', visualization: 'Line Chart' },
      { title: 'Blood Pressure Statistics', description: 'Analyze blood pressure measurements across age groups', dataType: 'Biostatistics', dataset: '200 patient records with age, systolic, diastolic BP', method: 'ANOVA, Linear regression', results: 'Significant increase with age (p<0.001), R²=0.67', visualization: 'Scatter Plot' },
      { title: 'Spectral Peak Analysis', description: 'Identify absorption peaks in UV-Vis spectra', dataType: 'Spectral', dataset: 'Wavelength (200-800nm) vs absorbance', method: 'Peak detection, Gaussian fitting', results: 'Major peaks at 270nm, 525nm. FWHM: 15nm, 22nm', visualization: 'Line Chart' },
      { title: 'Growth Curve Modeling', description: 'Model bacterial growth using logistic growth equation', dataType: 'Microbiological', dataset: 'Time (0-24h) vs OD600', method: 'Logistic regression', results: 'Lag phase: 2h, Generation time: 35min, Carrying capacity: OD 1.8', visualization: 'Line Chart' },
      { title: 'Crystal Structure Analysis', description: 'Analyze X-ray diffraction data for crystal structure determination', dataType: 'Crystallographic', dataset: '2θ vs intensity from powder XRD', method: 'Bragg analysis, Miller indices', results: 'FCC structure, a = 3.61Å (consistent with Cu)', visualization: 'Bar Chart' },
      { title: 'Reaction Kinetics Data', description: 'Determine reaction order from concentration-time data', dataType: 'Kinetic', dataset: 'Concentration vs time for decomposition reaction', method: 'Integrated rate law analysis', results: 'Second-order reaction, k = 0.0254 M⁻¹s⁻¹', visualization: 'Line Chart' },
      { title: 'Pendulum Period vs Length', description: 'Analyze relationship between pendulum length and period', dataType: 'Mechanical', dataset: 'Length (0.1-1.5m) vs period (10 trials each)', method: 'Power regression', results: 'T = 2.01L^0.498, R²=0.9994. g calculated: 9.78 m/s²', visualization: 'Scatter Plot' },
      { title: 'Protein Concentration Assay', description: 'Bradford assay standard curve for protein quantification', dataType: 'Biochemical', dataset: 'BSA concentration vs absorbance at 595nm', method: 'Linear regression', results: 'Linear range: 0.1-1.0 mg/mL, R²=0.9976', visualization: 'Line Chart' },
      { title: 'Population Genetics - Hardy-Weinberg', description: 'Test for Hardy-Weinberg equilibrium in simulated populations', dataType: 'Genetic', dataset: 'Genotype frequencies from 5 populations', method: 'Chi-square goodness of fit', results: '3/5 populations in HWE (p>0.05), 2 show selection pressure', visualization: 'Bar Chart' },
      { title: 'Electromagnetic Spectrum Analysis', description: 'Analyze emission spectra of hydrogen and helium', dataType: 'Spectral', dataset: 'Wavelength vs intensity for H and He emission', method: 'Line identification, Rydberg analysis', results: 'H Balmer series identified. Rydberg constant: 1.096×10⁷ m⁻¹', visualization: 'Line Chart' },
      { title: 'Soil pH Distribution', description: 'Statistical analysis of soil pH across different habitats', dataType: 'Environmental', dataset: '50 soil samples from 5 habitats', method: 'Descriptive stats, Kruskal-Wallis test', results: 'Forest: 5.2±0.4, Grassland: 6.8±0.3 (p<0.001)', visualization: 'Box Plot' },
      { title: 'Force vs Acceleration', description: 'Verify Newton\'s second law with cart and track experiments', dataType: 'Mechanical', dataset: 'Applied force (0.5-5N) vs acceleration (constant mass)', method: 'Linear regression', results: 'a = 1.98F + 0.02, R²=0.9991. Effective mass: 0.505kg', visualization: 'Scatter Plot' }
    ]);
    console.log('Data analysis seeded');

    // Molecular Structures (15)
    await MolecularStructure.bulkCreate([
      { name: 'Water', formula: 'H₂O', molecularWeight: 18.015, category: 'Inorganic', bondType: 'Covalent', properties: 'Polar, Hydrogen bonding, Universal solvent', structure: 'Bent geometry, 104.5° bond angle' },
      { name: 'Glucose', formula: 'C₆H₁₂O₆', molecularWeight: 180.156, category: 'Carbohydrate', bondType: 'Covalent', properties: 'Primary energy source, Reducing sugar', structure: 'Pyranose ring, chair conformation' },
      { name: 'Caffeine', formula: 'C₈H₁₀N₄O₂', molecularWeight: 194.19, category: 'Alkaloid', bondType: 'Covalent', properties: 'Stimulant, Bitter taste, Soluble in water', structure: 'Purine derivative, two fused rings' },
      { name: 'Ethanol', formula: 'C₂H₅OH', molecularWeight: 46.07, category: 'Alcohol', bondType: 'Covalent', properties: 'Volatile, Hydrogen bonding, Miscible with water', structure: 'Tetrahedral carbon, hydroxyl group' },
      { name: 'Sodium Chloride', formula: 'NaCl', molecularWeight: 58.44, category: 'Ionic', bondType: 'Ionic', properties: 'Crystalline solid, Electrolyte, High melting point', structure: 'FCC crystal lattice, 6-coordinate' },
      { name: 'Aspirin', formula: 'C₉H₈O₄', molecularWeight: 180.16, category: 'Pharmaceutical', bondType: 'Covalent', properties: 'Anti-inflammatory, Analgesic, Antipyretic', structure: 'Ester linkage, aromatic ring' },
      { name: 'DNA Nucleotide (Adenine)', formula: 'C₁₀H₁₃N₅O₃', molecularWeight: 267.24, category: 'Nucleic Acid', bondType: 'Covalent/Hydrogen', properties: 'Genetic information storage, Base pairing with Thymine', structure: 'Purine base + deoxyribose + phosphate' },
      { name: 'Carbon Dioxide', formula: 'CO₂', molecularWeight: 44.01, category: 'Inorganic', bondType: 'Covalent', properties: 'Greenhouse gas, Sublimes at -78.5°C', structure: 'Linear geometry, sp hybridized carbon' },
      { name: 'Hemoglobin', formula: 'C₂₉₅₂H₄₆₆₄N₈₁₂O₈₃₂S₈Fe₄', molecularWeight: 64500, category: 'Protein', bondType: 'Peptide/Coordinate', properties: 'Oxygen transport, Iron-containing heme groups', structure: 'Quaternary structure, 4 subunits with heme' },
      { name: 'Benzene', formula: 'C₆H₆', molecularWeight: 78.11, category: 'Aromatic', bondType: 'Covalent', properties: 'Aromatic, Planar, Delocalized electrons', structure: 'Planar hexagonal, sp2 hybridized' },
      { name: 'Methane', formula: 'CH₄', molecularWeight: 16.04, category: 'Hydrocarbon', bondType: 'Covalent', properties: 'Greenhouse gas, Natural gas component', structure: 'Tetrahedral geometry, sp3 hybridized' },
      { name: 'Acetylcholine', formula: 'C₇H₁₆NO₂⁺', molecularWeight: 146.21, category: 'Neurotransmitter', bondType: 'Covalent/Ionic', properties: 'Neurotransmitter, Muscle contraction, Memory', structure: 'Ester bond, quaternary ammonium' },
      { name: 'Chlorophyll a', formula: 'C₅₅H₇₂MgN₄O₅', molecularWeight: 893.51, category: 'Pigment', bondType: 'Coordinate/Covalent', properties: 'Photosynthesis, Light absorption (red/blue)', structure: 'Porphyrin ring with Mg²⁺ center, phytol tail' },
      { name: 'ATP', formula: 'C₁₀H₁₆N₅O₁₃P₃', molecularWeight: 507.18, category: 'Nucleotide', bondType: 'Covalent', properties: 'Energy currency of cells, Phosphoanhydride bonds', structure: 'Adenine + ribose + 3 phosphate groups' },
      { name: 'Insulin', formula: 'C₂₅₇H₃₈₃N₆₅O₇₇S₆', molecularWeight: 5808, category: 'Protein Hormone', bondType: 'Peptide/Disulfide', properties: 'Blood glucose regulation, 51 amino acids', structure: 'Two chains (A: 21aa, B: 30aa), 3 disulfide bonds' }
    ]);
    console.log('Molecular structures seeded');

    // Assessments (15)
    await Assessment.bulkCreate([
      { title: 'Chemistry Lab Safety Quiz', subject: 'Chemistry', type: 'Quiz', questions: '10 multiple choice questions on lab safety protocols', maxScore: 100, duration: '15 min', difficulty: 'beginner', aiGenerated: false },
      { title: 'Physics Midterm - Mechanics', subject: 'Physics', type: 'Exam', questions: '25 questions covering kinematics, dynamics, and energy', maxScore: 100, duration: '90 min', difficulty: 'intermediate', aiGenerated: false },
      { title: 'Biology Cell Structure Test', subject: 'Biology', type: 'Test', questions: '20 questions on organelles, membrane transport, and cell division', maxScore: 100, duration: '60 min', difficulty: 'beginner', aiGenerated: false },
      { title: 'Organic Chemistry Reactions', subject: 'Chemistry', type: 'Exam', questions: '30 questions on reaction mechanisms and synthesis', maxScore: 100, duration: '120 min', difficulty: 'advanced', aiGenerated: false },
      { title: 'Lab Report Rubric Assessment', subject: 'General', type: 'Rubric', questions: 'Evaluate: hypothesis, methodology, data, analysis, conclusion', maxScore: 50, duration: '30 min', difficulty: 'intermediate', aiGenerated: false },
      { title: 'Genetics Problem Set', subject: 'Biology', type: 'Problem Set', questions: '15 genetics problems: monohybrid, dihybrid, and linked genes', maxScore: 75, duration: '45 min', difficulty: 'intermediate', aiGenerated: true },
      { title: 'Electromagnetism Quiz', subject: 'Physics', type: 'Quiz', questions: '12 questions on electric fields, magnetic fields, and circuits', maxScore: 60, duration: '20 min', difficulty: 'intermediate', aiGenerated: true },
      { title: 'Biochemistry Enzymes Test', subject: 'Biochemistry', type: 'Test', questions: '18 questions on enzyme kinetics, regulation, and inhibition', maxScore: 90, duration: '50 min', difficulty: 'advanced', aiGenerated: false },
      { title: 'Ecology Field Study Report', subject: 'Biology', type: 'Report', questions: 'Comprehensive field study with data collection and analysis', maxScore: 100, duration: '1 week', difficulty: 'advanced', aiGenerated: false },
      { title: 'Thermodynamics Final', subject: 'Physics', type: 'Exam', questions: '35 questions on laws of thermodynamics, heat engines, entropy', maxScore: 100, duration: '120 min', difficulty: 'advanced', aiGenerated: false },
      { title: 'Microscopy Skills Practical', subject: 'Biology', type: 'Practical', questions: '5 specimens to identify and measure under microscope', maxScore: 50, duration: '30 min', difficulty: 'beginner', aiGenerated: false },
      { title: 'Chemical Equilibrium Quiz', subject: 'Chemistry', type: 'Quiz', questions: '10 questions on Le Chatelier, Ksp, and equilibrium calculations', maxScore: 50, duration: '20 min', difficulty: 'intermediate', aiGenerated: true },
      { title: 'Molecular Biology Techniques', subject: 'Biology', type: 'Test', questions: '22 questions on PCR, gel electrophoresis, cloning, sequencing', maxScore: 100, duration: '60 min', difficulty: 'advanced', aiGenerated: false },
      { title: 'Wave Physics Problem Set', subject: 'Physics', type: 'Problem Set', questions: '12 problems on interference, diffraction, and standing waves', maxScore: 60, duration: '40 min', difficulty: 'intermediate', aiGenerated: true },
      { title: 'Safety Training Certification', subject: 'Safety', type: 'Certification', questions: '50 comprehensive questions covering all safety modules', maxScore: 100, duration: '60 min', difficulty: 'intermediate', aiGenerated: false }
    ]);
    console.log('Assessments seeded');

    // Collaborations (15)
    await Collaboration.bulkCreate([
      { projectName: 'Water Quality Analysis', description: 'Collaborative study of local water sources for contaminants', members: 'Emily Watson, Marcus Chen, Sarah Park', subject: 'Environmental Chemistry', status: 'in-progress', deadline: new Date('2026-04-15'), notes: 'Collecting samples from 5 local water bodies' },
      { projectName: 'Solar Cell Efficiency', description: 'Measuring efficiency of different photovoltaic cell types', members: 'Priya Sharma, Hannah Kim, Alex Rivera', subject: 'Physics', status: 'in-progress', deadline: new Date('2026-04-20'), notes: 'Testing monocrystalline, polycrystalline, and thin-film cells' },
      { projectName: 'Antibiotic Resistance Study', description: 'Investigating antibiotic resistance patterns in soil bacteria', members: 'Maria Gonzalez, Tyler Brown, Jessica Nguyen', subject: 'Microbiology', status: 'planning', deadline: new Date('2026-05-01'), notes: 'Disk diffusion assays with multiple antibiotics' },
      { projectName: 'Bridge Design Challenge', description: 'Design and test load-bearing capacity of model bridges', members: 'James Rodriguez, Kevin Thompson, Daniel Lee', subject: 'Engineering Physics', status: 'completed', deadline: new Date('2026-03-10'), notes: 'Winning design held 45kg, used triangular truss structure' },
      { projectName: 'Plant Growth Hormones', description: 'Effects of auxin and gibberellin on plant growth rates', members: 'Amy Zhang, Sofia Martinez, Sarah Park', subject: 'Plant Biology', status: 'in-progress', deadline: new Date('2026-04-25'), notes: 'Testing 5 concentrations of each hormone on bean seedlings' },
      { projectName: 'Rocket Propulsion Lab', description: 'Design and launch water rockets to study propulsion physics', members: 'Marcus Chen, Alex Rivera, Kevin Thompson', subject: 'Aerodynamics', status: 'review', deadline: new Date('2026-03-25'), notes: 'Analyzing flight data from 10 launches' },
      { projectName: 'Biodiversity Survey', description: 'Campus biodiversity assessment using multiple sampling methods', members: 'Daniel Lee, Amy Zhang, Maria Gonzalez', subject: 'Ecology', status: 'in-progress', deadline: new Date('2026-04-30'), notes: 'Mapping 20 quadrats across 4 campus habitats' },
      { projectName: 'Polymer Properties Investigation', description: 'Compare mechanical properties of different polymer materials', members: 'Sofia Martinez, Emily Watson, Robert Wilson', subject: 'Materials Science', status: 'planning', deadline: new Date('2026-05-10'), notes: 'Testing tensile strength, elasticity, and thermal properties' },
      { projectName: 'Neural Network Modeling', description: 'Build a simple neural network to classify lab data', members: 'Hannah Kim, Priya Sharma, Jessica Nguyen', subject: 'Computational Science', status: 'in-progress', deadline: new Date('2026-04-18'), notes: 'Using Python/TensorFlow for classification of spectral data' },
      { projectName: 'Fermentation Kinetics', description: 'Study fermentation rates under different conditions', members: 'Tyler Brown, James Rodriguez, Maria Gonzalez', subject: 'Biochemistry', status: 'review', deadline: new Date('2026-03-28'), notes: 'CO2 production measured over 48 hours at 3 temperatures' },
      { projectName: 'Electromagnetic Shielding', description: 'Test effectiveness of different materials for EM shielding', members: 'Alex Rivera, Hannah Kim, Marcus Chen', subject: 'Electromagnetism', status: 'planning', deadline: new Date('2026-05-05'), notes: 'Testing copper, aluminum, and mu-metal at various frequencies' },
      { projectName: 'Drug Delivery Nanoparticles', description: 'Synthesize and characterize polymer nanoparticles for drug delivery', members: 'Sofia Martinez, Emily Watson, Sarah Park', subject: 'Nanochemistry', status: 'planning', deadline: new Date('2026-05-15'), notes: 'PLGA nanoparticles loaded with model drug' },
      { projectName: 'Renewable Energy Audit', description: 'Assess campus potential for renewable energy installations', members: 'Kevin Thompson, Priya Sharma, Daniel Lee', subject: 'Environmental Science', status: 'in-progress', deadline: new Date('2026-04-22'), notes: 'Solar irradiance data collection and wind speed monitoring' },
      { projectName: 'Gene Expression Analysis', description: 'RT-qPCR analysis of stress-responsive genes in plants', members: 'Jessica Nguyen, Amy Zhang, Tyler Brown', subject: 'Molecular Biology', status: 'in-progress', deadline: new Date('2026-04-28'), notes: 'Drought stress treatment at 3 time points' },
      { projectName: 'Acoustic Resonance Study', description: 'Map acoustic resonance patterns in different room geometries', members: 'Robert Wilson, James Rodriguez, Alex Rivera', subject: 'Acoustics', status: 'completed', deadline: new Date('2026-03-12'), notes: 'Identified resonant frequencies in 4 campus rooms' }
    ]);
    console.log('Collaborations seeded');

    // Lab Schedules (15)
    await LabSchedule.bulkCreate([
      { labName: 'General Chemistry Lab A', instructor: 'Dr. Sarah Chen', date: '2026-03-19', startTime: '09:00', endTime: '11:00', room: 'Room 105', capacity: 30, enrolled: 28, status: 'scheduled' },
      { labName: 'Physics Mechanics Lab', instructor: 'Dr. Michael Torres', date: '2026-03-19', startTime: '13:00', endTime: '15:00', room: 'Room 201', capacity: 25, enrolled: 24, status: 'scheduled' },
      { labName: 'Biology Cell Lab', instructor: 'Dr. Lisa Wang', date: '2026-03-19', startTime: '10:00', endTime: '12:00', room: 'Room 301', capacity: 28, enrolled: 26, status: 'scheduled' },
      { labName: 'Organic Chemistry Lab', instructor: 'Dr. Sarah Chen', date: '2026-03-20', startTime: '14:00', endTime: '17:00', room: 'Room 105', capacity: 24, enrolled: 22, status: 'scheduled' },
      { labName: 'Electronics Lab', instructor: 'Dr. David Park', date: '2026-03-20', startTime: '09:00', endTime: '11:00', room: 'Room 501', capacity: 20, enrolled: 18, status: 'scheduled' },
      { labName: 'Microbiology Lab', instructor: 'Dr. Lisa Wang', date: '2026-03-20', startTime: '13:00', endTime: '15:00', room: 'Room 403', capacity: 22, enrolled: 20, status: 'scheduled' },
      { labName: 'Physics Optics Lab', instructor: 'Dr. Michael Torres', date: '2026-03-21', startTime: '10:00', endTime: '12:00', room: 'Room 501', capacity: 25, enrolled: 23, status: 'scheduled' },
      { labName: 'Biochemistry Lab', instructor: 'Dr. James Liu', date: '2026-03-21', startTime: '14:00', endTime: '17:00', room: 'Room 302', capacity: 20, enrolled: 19, status: 'scheduled' },
      { labName: 'Genetics Lab', instructor: 'Dr. Lisa Wang', date: '2026-03-22', startTime: '09:00', endTime: '12:00', room: 'Room 401', capacity: 24, enrolled: 22, status: 'scheduled' },
      { labName: 'Analytical Chemistry Lab', instructor: 'Dr. Sarah Chen', date: '2026-03-22', startTime: '13:00', endTime: '16:00', room: 'Room 302', capacity: 22, enrolled: 20, status: 'scheduled' },
      { labName: 'Environmental Science Lab', instructor: 'Dr. Maria Santos', date: '2026-03-23', startTime: '10:00', endTime: '13:00', room: 'Room 105', capacity: 28, enrolled: 25, status: 'scheduled' },
      { labName: 'Molecular Biology Lab', instructor: 'Dr. James Liu', date: '2026-03-23', startTime: '14:00', endTime: '17:00', room: 'Room 401', capacity: 20, enrolled: 18, status: 'scheduled' },
      { labName: 'Materials Science Lab', instructor: 'Dr. David Park', date: '2026-03-24', startTime: '09:00', endTime: '12:00', room: 'Room 201', capacity: 22, enrolled: 20, status: 'scheduled' },
      { labName: 'Computational Physics Lab', instructor: 'Dr. Michael Torres', date: '2026-03-24', startTime: '13:00', endTime: '15:00', room: 'Room 501', capacity: 25, enrolled: 22, status: 'scheduled' },
      { labName: 'General Chemistry Lab B', instructor: 'Dr. Sarah Chen', date: '2026-03-25', startTime: '09:00', endTime: '11:00', room: 'Room 105', capacity: 30, enrolled: 27, status: 'scheduled' }
    ]);
    console.log('Lab schedules seeded');

    // Research Papers (15)
    await ResearchPaper.bulkCreate([
      { title: 'Novel Approaches to Green Chemistry in Undergraduate Labs', authors: 'Dr. Sarah Chen, Emily Watson', abstract: 'This paper presents sustainable chemistry experiments suitable for undergraduate education', subject: 'Chemistry', keywords: 'green chemistry, sustainability, education', status: 'published', journal: 'Journal of Chemical Education' },
      { title: 'Virtual Physics Labs: Effectiveness in Remote Learning', authors: 'Dr. Michael Torres, Priya Sharma', abstract: 'Comparative study of virtual vs physical physics laboratories in student learning outcomes', subject: 'Physics Education', keywords: 'virtual labs, remote learning, physics', status: 'published', journal: 'Physics Education Research' },
      { title: 'CRISPR Applications in Teaching Genetics', authors: 'Dr. Lisa Wang, Jessica Nguyen', abstract: 'Integration of CRISPR-Cas9 demonstrations in undergraduate genetics curriculum', subject: 'Genetics', keywords: 'CRISPR, genetics education, gene editing', status: 'review', journal: 'Biochemistry and Molecular Biology Education' },
      { title: 'AI-Assisted Lab Report Assessment', authors: 'Dr. James Liu, Hannah Kim', abstract: 'Evaluating machine learning models for automated lab report grading and feedback', subject: 'Education Technology', keywords: 'AI, assessment, machine learning, lab reports', status: 'draft', journal: 'Computers & Education' },
      { title: 'Microplastics in Local Water Systems', authors: 'Dr. Maria Santos, Daniel Lee, Amy Zhang', abstract: 'Quantification and characterization of microplastic pollution in regional water sources', subject: 'Environmental Science', keywords: 'microplastics, water quality, pollution', status: 'review', journal: 'Environmental Science & Technology' },
      { title: 'Low-Cost Spectrophotometer for Education', authors: 'Dr. David Park, Alex Rivera', abstract: 'Design and validation of an affordable LED-based spectrophotometer for teaching labs', subject: 'Instrumentation', keywords: 'spectrophotometer, low-cost, education', status: 'published', journal: 'Journal of Chemical Education' },
      { title: 'Enzyme Kinetics Simulation Software', authors: 'Dr. James Liu, James Rodriguez', abstract: 'Development of interactive enzyme kinetics simulation for biochemistry education', subject: 'Biochemistry', keywords: 'enzyme kinetics, simulation, software', status: 'draft', journal: 'Biochemistry and Molecular Biology Education' },
      { title: 'Student Misconceptions in Thermodynamics', authors: 'Dr. Michael Torres, Marcus Chen', abstract: 'Identifying and addressing common student misconceptions about heat and temperature', subject: 'Physics Education', keywords: 'misconceptions, thermodynamics, conceptual change', status: 'published', journal: 'American Journal of Physics' },
      { title: 'Biodiversity Assessment Using eDNA', authors: 'Dr. Maria Santos, Maria Gonzalez, Tyler Brown', abstract: 'Environmental DNA metabarcoding for rapid biodiversity assessment on campus', subject: 'Ecology', keywords: 'eDNA, biodiversity, metabarcoding', status: 'in-progress', journal: 'Molecular Ecology Resources' },
      { title: 'Gamification in Chemistry Laboratory Education', authors: 'Dr. Sarah Chen, Sofia Martinez', abstract: 'Effects of gamification elements on student engagement and learning in chemistry labs', subject: 'Chemistry Education', keywords: 'gamification, engagement, chemistry labs', status: 'review', journal: 'Chemistry Education Research and Practice' },
      { title: 'Arduino-Based Physics Experiments', authors: 'Dr. David Park, Hannah Kim, Kevin Thompson', abstract: 'Collection of Arduino-controlled experiments for undergraduate physics laboratories', subject: 'Physics', keywords: 'Arduino, sensors, data acquisition, physics labs', status: 'published', journal: 'European Journal of Physics' },
      { title: 'Antibiotic Resistance Patterns in Campus Soil', authors: 'Dr. Lisa Wang, Maria Gonzalez', abstract: 'Survey of antibiotic-resistant bacteria in university campus soil environments', subject: 'Microbiology', keywords: 'antibiotic resistance, soil bacteria, campus', status: 'draft', journal: 'Applied and Environmental Microbiology' },
      { title: 'Virtual Reality in Anatomy Education', authors: 'Dr. Lisa Wang, Sarah Park', abstract: 'Effectiveness of VR-based anatomy instruction compared to traditional dissection', subject: 'Biology Education', keywords: 'virtual reality, anatomy, dissection, VR', status: 'review', journal: 'Anatomical Sciences Education' },
      { title: 'Machine Learning for Spectral Analysis', authors: 'Dr. James Liu, Robert Wilson, Priya Sharma', abstract: 'Application of neural networks for automated spectral peak identification and analysis', subject: 'Analytical Chemistry', keywords: 'machine learning, spectral analysis, neural networks', status: 'in-progress', journal: 'Analytical Chemistry' },
      { title: 'Carbon Footprint of University Laboratories', authors: 'Dr. Maria Santos, Kevin Thompson, Daniel Lee', abstract: 'Comprehensive carbon footprint analysis of laboratory operations with sustainability recommendations', subject: 'Sustainability', keywords: 'carbon footprint, sustainability, green labs', status: 'draft', journal: 'International Journal of Sustainability in Higher Education' }
    ]);
    console.log('Research papers seeded');

    // Virtual Lab Sessions (15)
    await VirtualLabSession.bulkCreate([
      { name: 'Introduction to Titration', description: 'Step-by-step virtual titration with real-time pH monitoring', subject: 'Chemistry', labType: 'Analytical', objectives: 'Learn titration technique, endpoint detection, and concentration calculation', instructions: 'Follow the virtual burette controls to add NaOH to the acid solution', duration: '45 min', difficulty: 'beginner' },
      { name: 'Projectile Launch Simulator', description: 'Interactive projectile motion with adjustable parameters', subject: 'Physics', labType: 'Mechanics', objectives: 'Understand the relationship between launch angle, velocity, and range', instructions: 'Adjust angle and velocity sliders, observe trajectory and landing position', duration: '30 min', difficulty: 'beginner' },
      { name: 'Virtual Microscopy - Cell Types', description: 'Explore different cell types using virtual microscope with zoom controls', subject: 'Biology', labType: 'Cell Biology', objectives: 'Identify and compare plant, animal, and bacterial cells', instructions: 'Navigate through prepared slides, adjust magnification, identify organelles', duration: '40 min', difficulty: 'beginner' },
      { name: 'Chemical Equilibrium Simulator', description: 'Manipulate conditions to observe equilibrium shifts in real-time', subject: 'Chemistry', labType: 'Physical Chemistry', objectives: 'Observe Le Chatelier\'s principle in action', instructions: 'Change temperature, pressure, and concentration; observe equilibrium response', duration: '35 min', difficulty: 'intermediate' },
      { name: 'Circuit Builder', description: 'Build and test virtual electrical circuits with measurements', subject: 'Physics', labType: 'Electronics', objectives: 'Build series and parallel circuits, verify Ohm\'s law and Kirchhoff\'s laws', instructions: 'Drag components to breadboard, connect wires, use virtual multimeter', duration: '50 min', difficulty: 'intermediate' },
      { name: 'DNA Replication Walkthrough', description: 'Interactive animation of DNA replication process', subject: 'Biology', labType: 'Molecular Biology', objectives: 'Understand the steps of DNA replication and the role of each enzyme', instructions: 'Follow the replication fork, identify enzymes, answer checkpoint questions', duration: '35 min', difficulty: 'intermediate' },
      { name: 'Organic Reaction Mechanisms', description: 'Step through organic reaction mechanisms with electron movement', subject: 'Chemistry', labType: 'Organic Chemistry', objectives: 'Understand SN1, SN2, E1, and E2 reaction mechanisms', instructions: 'Draw curved arrows for electron movement, predict products', duration: '60 min', difficulty: 'advanced' },
      { name: 'Wave Interference Sandbox', description: 'Create and observe wave interference patterns in 2D', subject: 'Physics', labType: 'Waves', objectives: 'Understand constructive and destructive interference', instructions: 'Place wave sources, adjust frequency and amplitude, observe patterns', duration: '30 min', difficulty: 'beginner' },
      { name: 'Virtual Dissection - Frog', description: 'Complete virtual frog dissection with organ identification', subject: 'Biology', labType: 'Anatomy', objectives: 'Identify major organ systems and understand their functions', instructions: 'Use virtual tools to dissect, pin, and label organs', duration: '55 min', difficulty: 'intermediate' },
      { name: 'Spectroscopy Analysis Lab', description: 'Analyze IR, NMR, and Mass spectra to identify unknown compounds', subject: 'Chemistry', labType: 'Analytical', objectives: 'Interpret spectroscopic data for structural determination', instructions: 'Examine each spectrum, identify functional groups, determine structure', duration: '60 min', difficulty: 'advanced' },
      { name: 'Gravitational Orbit Simulator', description: 'Model planetary orbits and gravitational interactions', subject: 'Physics', labType: 'Astrophysics', objectives: 'Understand Kepler\'s laws and gravitational mechanics', instructions: 'Set initial conditions for planets, observe orbital motion, verify Kepler\'s laws', duration: '40 min', difficulty: 'intermediate' },
      { name: 'Ecosystem Dynamics Model', description: 'Simulate predator-prey dynamics and ecosystem balance', subject: 'Biology', labType: 'Ecology', objectives: 'Understand population dynamics and ecosystem stability', instructions: 'Set initial population sizes, observe Lotka-Volterra dynamics', duration: '45 min', difficulty: 'intermediate' },
      { name: 'Calorimetry Virtual Lab', description: 'Measure heat of reaction using virtual coffee-cup calorimeter', subject: 'Chemistry', labType: 'Thermochemistry', objectives: 'Calculate enthalpy changes from temperature data', instructions: 'Mix reagents in virtual calorimeter, record temperature, calculate ΔH', duration: '40 min', difficulty: 'beginner' },
      { name: 'Quantum Mechanics Visualizer', description: 'Visualize wave functions, probability densities, and quantum tunneling', subject: 'Physics', labType: 'Quantum Physics', objectives: 'Understand quantum mechanical concepts through visualization', instructions: 'Explore hydrogen atom orbitals, observe quantum tunneling probability', duration: '50 min', difficulty: 'advanced' },
      { name: 'Protein Folding Simulation', description: 'Simulate protein folding and explore structure-function relationships', subject: 'Biochemistry', labType: 'Structural Biology', objectives: 'Understand primary to quaternary protein structure', instructions: 'Input amino acid sequence, observe folding, analyze 3D structure', duration: '55 min', difficulty: 'advanced' }
    ]);
    console.log('Virtual lab sessions seeded');

    console.log('\n✅ All seed data inserted successfully!');
    console.log('Total features seeded: 15');
    console.log('Items per feature: 15');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
